apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: go-web.local
    http:
      paths: 
      - path: /home
        pathType: Prefix
        backend:
          service:
            name: go-app-service
            port:
              number: 30007