apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080         # Port that the service will expose
      targetPort: 8080   # Port on the container that the service should forward traffic to
      nodePort: 30007  